# Glossary {.unnumbered}


**Accounting** - the information system that identifies and records the economic events of an organization and then communicates them to a wide variety of interested users.

**accounts receivable** - the operation of receiving money in the future from customers. This is an asset as they represent an economic resource (cash) and will be eventually collected.

**accounts payable** - short term liability from some expenses when a company purchases inventory or supplies on credit from suppliers.

**interest payable** - the outstanding (unpaid) liability amounts owed to various lenders and creditors

- dividends payable, salaries payable, property payable, sales tax payable

Business goal is to sell a good or service for a price greater than the cost of producing or purchasing the good or providing the service, plus the cost of operating the business.

**net income** - revenues are greater than the expenses incurred to generate the revenues. (net earnings, profit)


**Internal users** - internal accounting information manage companies, non-profits and government organizations, help these organizations make decisions required to run the company.

**External users** - do not have access to internal accounting information, the general public.

Primary users:

- investors : use accounting information to make decisions to buy, hold, or sell their ownership shares

- lenders: use accounting information to evaluate the risks of lending money
- creditors: use accounting information to decide whether or not to grant credit to a customer


**Proprietorship** - a business owned by one person, (sole proprietorship)

**reporting entity concept** - the separation of business and personal records of economic activity, to be distinct from activities of the owner and all other economic entities.


**Partnerships** - a business owned by more than one person


**Corporations** - a business organized as a separate legal entity owned by shareholders and is the most complex form of business to establish.


**Public corporations** - corporations that share their shares/stocks on the Stock Exchange, and are required to distribute their financial statements to investors, lenders, creditors and the public every three months.


SEDAR - system for electronic document analysis and retrieval, financial statement website for Canadian public corporations


**Private corporations** - corporations that issue shares but they do not make them public, nor are the shares traded on the Stock Exchange.


**GAAP** - generally accepted accounting principles, which are rules,practices, procedures for recording and reporting economic events.

**IFRS** - public traded corporations must use the international financial reporting standards

**ASPE** - for private corporations must use accounting standards for private enterprises


business activities = financing (money to expand operations), investing (building, renovations, purchasing) and operating (activities that finance company)


### Financial activities

Capital (money) is required to start any business. Methods for raising funds for
corporations:

- issuing (selling) shares (equity financing)
- borrowing money (debt financing)

common shares (share capital) - the amount paid by investors for shares of ownership in a company, these investors are _shareholders_

dividends - payments that distribute a portion of income to shareholders

liabilities - amounts owed to lender and creditors in form of debt and obligations


bank indebtedness - this liability is when a company uses its operating line of credit to cover cash shortfalls and overdraws its bank account


Corporations can borrow using a short-term bank loan payable (note payable) or long term debt which can include mortgages payable, bonds payable, finance lease obligations and other types of debt securities.



### Investing activities

Post fund raising, the money i sused for investing activities, which include purchase or sale of long lived assets that a company needs in order to operate.

**Assets** - resources that a company owns or controls. "property, plant and equipment" phrase is used to sum up all the assets of a company.

**goodwill** - when a company pays more than the value of purchased company's net identifiable assets when acquiring a company

**intangible assets** - assets that do not have any physical substance themselves but represent a privilege or a right granted to a company


> purchase is outflow, sale is inflow


### Operating activities

A company has raised funds and investments, it now does operating activities.

Sources of income (finance income):

- sales revenue
- service revenue
- interest revenue
- rent revenue


**accounts receivable** - the operation of receiving money in the future from customers. This is an asset as they represent an economic resource (cash) and will be eventually collected.


- supplies are short term assets used in daily operations

- inventory are items held for future sale to customers. When items are sold, they become an expense


The cost of inventory sold is an expense called _cost of goods sold_.


- expenses are decreases in economic resources
- other names for expenses = _cost of sales, selling operating and administrative expenses, and income tax expense_. 


**accounts payable** - short term liability from some expenses when a company purchases inventory or supplies on credit from suppliers.

**interest payable** - the outstanding (unpaid) liability amounts owed to various lenders and creditors

- dividends payable, salaries payable, property payable, sales tax payable


Business goal is to sell a good or service for a price greater than the cost of producing or purchasing the good or providing the service, plus the cost of operating the business.

**net income** - revenues are greater than the expenses incurred to generate the revenues. (net earnings, profit)




### Financial statements

For external reporting purposes to provide information on assets,liabilities, shareholders equity and cash flow.


There are 4 required financial statements:

1. **income statement** - reports revenues and expenses, showing how a company's operations performed during a period of time

2. **statement of changes in equity** - shows changes in each component of shareholders equity (common shares and retained earnings) and total equity during period of time

3. **statement of financial position** - what a company owns (assets), what it owes (liabilities) and resulting difference (shareholder equity) at a specific point in time

4. **statement of cash flows** - where a company obtained cash during a period of time and how that cash was used



#### Statement of changes in Equity

Account balances at the beginning of the period and ends with the account balances at the end of the period. The ownership interest in a company is known as _shareholder's equity_, which is the total shareholder's equity including:

- share capital : the amounts contributed by the shareholders in exchange for shares of ownership
- retained earnings
- other accounts

common shares (end of period) = 
            common shares (begin of period) 
            + common shares issued (sold) 
            - common shares repurchased
            

**retained earnings** - the cumulative amounts of net income that have been retained in the corporation (not distributed as dividends to shareholders). If retained earnings is negative that is net loesses have exceeded net income (deficit)





